version: '3'
services:
  mssql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Unknown#2022"
    ports:
      - "1433:1433"
    volumes:
      - C:\dados\volumes\sqlserver:/var/opt/mssql/data
  book-app:
    build: .
    depends_on:
      - mssql-server  
    environment:
      DbServer: "mssql-server"
      DbPort: "1433"
      DbUser: "sa"
      Password: "Unknown#2022"
      Database: "BooksDB"
    ports:
      - "8090:80"     
